version: '3.9'
services:
  redis:
    image: redis:6.2-alpine
    command: redis-server
    ports:
      - '6379:6379'
  server:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - '80:80'

